### ISSUE TITLE
Getting issue while deploying the app on bluemix

### ISSUE THREAD

**Issue by sakshiag** [IBM-Bluemix/nodejs-cloudantdb-crud-example#9]
ERR /home/vcap/app/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
**2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR const Hoek = require('hoek');
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR ^^^^^
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR SyntaxError: Use of const in strict mode.**
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at exports.runInThisContext (vm.js:73:16)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Module._compile (module.js:443:25)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (module.js:478:10)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Module.load (module.js:355:32)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Function.Module._load (module.js:310:12)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Module.require (module.js:365:17)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at require (module.js:384:17)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Object.<anonymous> (/home/vcap/app/node_modules/request/node_modules/hawk/lib/index.js:5:33)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Module._compile (module.js:460:26)
2017-09-26T15:16:00.91+0530 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (module.js:478:10)
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! Linux 4.4.0-75-generic
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! node v0.12.18
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! npm  v2.15.11
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! code ELIFECYCLE
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! NodejsCloudantExample@0.0.1 start: `node app.js`
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! Exit status 1
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! 
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! Failed at the NodejsCloudantExample@0.0.1 start script 'node app.js'.
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! This is most likely a problem with the NodejsCloudantExample package,
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! not with npm itself.
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! Tell the author that this fails on your system:
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR!     node app.js
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! You can get information on how to open an issue for this project with:
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR!     npm bugs NodejsCloudantExample
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! Or if that isn't available, you can get their info via:
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! 
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR!     npm owner ls NodejsCloudantExample
2017-09-26T15:16:00.95+0530 [APP/PROC/WEB/0]ERR npm ERR! There is likely additional logging output above.
2017-09-26T15:16:00.99+0530 [APP/PROC/WEB/0]ERR npm ERR! Please include the following file with any support request:
2017-09-26T15:16:00.99+0530 [APP/PROC/WEB/0]ERR npm ERR!     /home/vcap/app/npm-debug.log

As per my investigation, we need to use the latest nodejs version v8.4.0 in package.json

**Comment by emoulder** [comment]
I have the latest version of node.js 9.11.1 and still getting error.  I've seen several remedies out there including creating a package-lock.json file but none have worked.  

Has anyone else resolved this issue?  I actually had this running last year with modifications and wanted to use for something else but can't get past this.
